default_platform(:ios)
fastlane_require 'xcodeproj'


def set_all_xcodeproj_version_and_build_numbers(version_number, platform)
    project = Xcodeproj::Project.open('../ZipFinder.xcodeproj')
    targets = project.targets
    if platform == "ios"
      targets = targets.select { |target| target.name == "ZipFinder" }
    elsif platform == "macos"
      targets = targets.select { |target| target.name == "ZipFinderForMacOS" }
    else
      UI.user_error!("Invalid platform: #{platform}, allowed values are: macos")
    end
    
    build_number = latest_testflight_build_number(platform: platform) + 1

    targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["MARKETING_VERSION"] = version_number
        config.build_settings["CURRENT_PROJECT_VERSION"] = build_number
      end
    end
    project.save
end

desc "Updates the app's `MARKETING_VERSION` based on the branch name if needed."
lane :update_version_number_if_needed do
  split_git_ref = ENV["CI_BRANCH"].split("/", -1)
  
  if split_git_ref.length != 3
    UI.user_error!("Invalid branch name: #{ENV["CI_BRANCH"]}, expected format: release/{platform}/{version}")
  end


  version_number = split_git_ref.last
  platform = split_git_ref[1]
  set_all_xcodeproj_version_and_build_numbers(version_number, platform.downcase)
  
  if git_status(path: "ZipFinder.xcodeproj/project.pbxproj").empty?
    puts "🚀 Nothing to commit, pushing the same version again!"
  else
    Dir.chdir("..") do
      sh("git add ZipFinder.xcodeproj/project.pbxproj")
      sh("git commit -m '[ci skip] [🚀 release #{platform}] Updating version to: #{version_number}'")
    
      # Push with personal access token to enable permissions in Xcode Cloud
      sh("git push https://polpielladev:#{ENV["GITHUB_TOKEN"]}@github.com/polpielladev/zip-finder.git")
    end
  end
end

desc "Generate profiles and certificates"
lane :generate_profiles_and_certificates do
    sync_code_signing(
        type: "appstore",
        app_identifier: ["dev.polpiella.ZipFinder"],
        readonly: false
    )

    sync_code_signing(
        type: "development",
        app_identifier: ["dev.polpiella.ZipFinder"],
        readonly: false
    )
end

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    setup_ci

    sync_code_signing(
      type: "appstore",
      app_identifier: ["dev.polpiella.ZipFinder"],
      readonly: true
  )

    increment_build_number(xcodeproj: "ZipFinder.xcodeproj")
    build_app(scheme: "ZipFinder")
    upload_to_app_store
  end
end

platform :macos do
  desc "Push a new release build to the App Store"
  lane :release do
    setup_ci

    sync_code_signing(
      type: "appstore",
      app_identifier: ["dev.polpiella.ZipFinder"],
      readonly: true
  )

    increment_build_number(xcodeproj: "ZipFinderForMacOS.xcodeproj")
    build_app(scheme: "ZipFinder")
    upload_to_app_store
  end
end
