name: Release Build

on:
  push:
    branches:
      - "release/ios/*.*.*"
      - "release/macos/*.*.*"
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to build for"
        required: true
        default: "ios"
        type: choice
        options:
          - ios
          - macos
      version:
        description: "Version number"
        required: true
        default: "1.0.0"
        type: string

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run release fastlane lane
        run: |
          bundle exec fastlane release_from_branch
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_BRANCH: ${{ github.ref_name }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
